#!/bin/bash
if [ ${#} -ne 2 ] ; then
    echo "Incorrect number of command line arguments!"
    exit 1
fi
for word in `cat ${1}` ; do
    tfile=$(mktemp)
    trash=$(mktemp)
    if [ ! -f ${word}.in ] ; then
        echo "No ${word}.in file"
        exit 2
    fi
    if [ ! -f ${word}.out ] ; then
        echo "No ${word}.out file"
        exit 3
    fi 
    ./${2} < ${word}.in > "${tfile}"
    diff ${word}.out "${tfile}" > "${trash}"
    if [ ${?} -ne 0 ] ; then
        echo "Test failed: ${word}"
        echo "Input:"
        cat ${word}.in
        echo "Expected:"
        cat ${word}.out
        echo "Actual:"
        cat "${tfile}"
    fi
    rm "${tfile}"
    rm "${trash}"
done
